### ISSUE TITLE
Allow Downloading

### ISSUE THREAD

**Issue by guaraqe** [ItzBlitz98/streamflix#1]
I just tested something simple, and by putting wget as my video player, it downloaded the stream without problem. The only buts is that that the name of the file is giant, but that's easy to change. It is probably very easy to add it as a functionality to the program, probably, like after selecting the stream asking if you want to watch it or download.

**Comment by ItzBlitz98** [comment]
If you set the player to something like this: 

```
curl -o foo.mp4 -L 
```

Curl can download the file using a specified name, I'll take a look see if its feasible to add a download function.

**Comment by ItzBlitz98** [comment]
Ok added a download functionality its fairly crude as i'm assuming all files are going to be a .mp4.

If you find any bugs / issues let me know.

Edit:

Should state how to do it, If you open up the config.yaml file and add a download location after selecting the link it will prompt you to stream or download the file.

**Comment by guaraqe** [comment]
Just tested, it works great! I hadn't seen the download location on the options before, that's why it wasn't working. Thanks!
