### ISSUE TITLE
Reddit subs

### ISSUE THREAD

**Issue by walidsa3d** [ItzBlitz98/streamflix#2]
Some Reddit subs post links to movies (hosted mainly on youtube), it would be nice if you add them.
http://www.reddit.com/r/fullmoviesonyoutube/
http://www.reddit.com/r/fullforeignmovies/

**Comment by ItzBlitz98** [comment]
Hey Walidsa thanks for checking out Streamflix :)

Sure i'll get those added thanks for the suggestion.

**Comment by ItzBlitz98** [comment]
Added this in 0c6899186cbad94c2f27abaabca99a4d8fc5f222

If you open the config file you can add more subreddits yourself :+1:

**Comment by walidsa3d** [comment]
thanks, you're wonderful.
