### ISSUE TITLE
slow streams

### ISSUE THREAD

**Issue by walidsa3d** [ItzBlitz98/streamflix#4]
Youtube streams seem so slow on VLC and since their work well in the browser, I guess something is wrong (maybe you need to implement some kind of buffering)

**Comment by ItzBlitz98** [comment]
Ok i have pushed a new config section to add a player command option, By default players don't set a cache.

Open up the config and put this into the player_arg_cmd section (between 1000 and 10000 is recommended):

```
--file-caching="10000" --network-caching="10000"
```

This should give vlc some more breathing room.

PS: i don't actually know if both are required i use mpv and that just has one option i noticed vlc has two so i just added two to the example.

**Comment by walidsa3d** [comment]
Thanks, it works better now.

**Comment by ItzBlitz98** [comment]
Nice i can close this then :+1:
