### ISSUE TITLE
Youtube Subtitles

### ISSUE THREAD

**Issue by walidsa3d** [ItzBlitz98/streamflix#5]
Some Youtube videos have subtitles, why not use them instead of subtitles downloaded from OpenSubtitles?

**Comment by ItzBlitz98** [comment]
This is something i have thought about i'll take a look at what kind of api's youtube has for that (if any) and report back.

Thanks for the suggestion :+1:

**Comment by ItzBlitz98** [comment]
Sorry i haven't responded as fast as i would have liked to i have been pretty busy as of late.

Anyway i have taken a look at this and youtube requires authentication from oauth to be able to download subtitles from the api, I have no idea how i would do that from some simple questions i would prefer this app to ask. Simply put this is far too complicated sorry about that :(
